/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tarccompiler;

import files.ReadFile;
import java.awt.BorderLayout;
import java.awt.Color;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author charles_yu102
 */
public class CompilerGUI extends javax.swing.JFrame {

    // Attributes
    File file;
    
    /**
     * Creates new form CompilerGUI
     */
    public CompilerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fcOpenFile = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        fileTree = new javax.swing.JTree();
        btnCompile = new javax.swing.JButton();
        btnOpenFile = new javax.swing.JButton();
        btnNewFile = new javax.swing.JButton();
        tpCode = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taCode = new javax.swing.JTextArea();
        labelStatus = new javax.swing.JLabel();
        tpOutput = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        taOutput = new javax.swing.JTextArea();
        btnCloseFile = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        itemNewFile = new javax.swing.JMenuItem();
        itemOpenFile = new javax.swing.JMenuItem();
        itemSave = new javax.swing.JMenuItem();
        itemSaveAs = new javax.swing.JMenuItem();
        itemQuit = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();
        menuHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TARC Compiler");
        setLocation(new java.awt.Point(200, 0));

        jScrollPane1.setViewportView(fileTree);

        btnCompile.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        btnCompile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tarccompiler/resources/compile.png"))); // NOI18N
        btnCompile.setText("Compile Code");
        btnCompile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompileActionPerformed(evt);
            }
        });

        btnOpenFile.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        btnOpenFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tarccompiler/resources/open.png"))); // NOI18N
        btnOpenFile.setText("Open File");
        btnOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenFileActionPerformed(evt);
            }
        });

        btnNewFile.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        btnNewFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tarccompiler/resources/new.png"))); // NOI18N
        btnNewFile.setText("New File");
        btnNewFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewFileActionPerformed(evt);
            }
        });

        taCode.setBackground(new java.awt.Color(51, 51, 51));
        taCode.setColumns(20);
        taCode.setForeground(new java.awt.Color(51, 204, 0));
        taCode.setRows(5);
        taCode.setCaretColor(new java.awt.Color(255, 255, 0));
        jScrollPane2.setViewportView(taCode);

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
        );

        tpCode.addTab("[No Name]", jPanel3);

        labelStatus.setText("Status");

        taOutput.setColumns(20);
        taOutput.setForeground(new java.awt.Color(255, 0, 0));
        taOutput.setRows(5);
        jScrollPane4.setViewportView(taOutput);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
        );

        tpOutput.addTab("Output:", jPanel1);

        btnCloseFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tarccompiler/resources/close.png"))); // NOI18N
        btnCloseFile.setText("Close File");

        menuFile.setText("File");

        itemNewFile.setText("New File");
        itemNewFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNewFileActionPerformed(evt);
            }
        });
        menuFile.add(itemNewFile);

        itemOpenFile.setText("Open File...");
        itemOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOpenFileActionPerformed(evt);
            }
        });
        menuFile.add(itemOpenFile);

        itemSave.setText("Save");
        menuFile.add(itemSave);

        itemSaveAs.setText("Save As...");
        menuFile.add(itemSaveAs);

        itemQuit.setText("Quit");
        menuFile.add(itemQuit);

        menuBar.add(menuFile);

        menuAbout.setText("About");
        menuBar.add(menuAbout);

        menuHelp.setText("Help");
        menuBar.add(menuHelp);

        setJMenuBar(menuBar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(btnNewFile)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnOpenFile)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnCompile)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnCloseFile)
                .add(0, 0, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(tpOutput)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, tpCode))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 139, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(labelStatus)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnNewFile, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(btnOpenFile)
                    .add(btnCompile)
                    .add(btnCloseFile))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .add(tpCode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 442, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(tpOutput))
                    .add(layout.createSequentialGroup()
                        .add(15, 15, 15)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 564, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(labelStatus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCompileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompileActionPerformed
        // TODO add your handling code here:
        
        // Instantiate classes for source code compilation here
    }//GEN-LAST:event_btnCompileActionPerformed

    private void btnOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFileActionPerformed
        // TODO add your handling code here:
        openFile();
    }//GEN-LAST:event_btnOpenFileActionPerformed

    private void btnNewFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewFileActionPerformed
        // TODO add your handling code here:
        newFile();
    }//GEN-LAST:event_btnNewFileActionPerformed

    private void itemNewFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNewFileActionPerformed
        // TODO add your handling code here:
        newFile();
    }//GEN-LAST:event_itemNewFileActionPerformed

    private void itemOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOpenFileActionPerformed
        // TODO add your handling code here:
        openFile();
    }//GEN-LAST:event_itemOpenFileActionPerformed

    // Methods
    
    private String parseFileName(String file){
        String filename = "";
        String delim = "/";
        String[] files = file.split(delim);
        filename = files[files.length-1];
        return filename;
    }
    
    private void newFile(){
        if(tpCode.getTabCount() == 1 && tpCode.getTitleAt(0).equals("[No Name]")){
            // No need to add tab
        }else {
            // Add a new tab
            JPanel panel = new JPanel();
            panel.setLayout(new BorderLayout());

            JTextArea newCodeArea = new JTextArea();
            newCodeArea.setBackground(new Color(51,51,51));
            newCodeArea.setForeground(new Color(51,204,0));
            newCodeArea.setCaretColor(new Color(255,255,0));
            JScrollPane scroll = new JScrollPane(newCodeArea);
            panel.add(scroll, BorderLayout.CENTER);

            tpCode.addTab("[No Name]", panel);
        }
    }
    
    private void openFile(){
        FileNameExtensionFilter ft = new FileNameExtensionFilter("TARC Codes", "tarc");
        fcOpenFile.addChoosableFileFilter(ft);
        
        int returnVal = fcOpenFile.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION){
            this.file = fcOpenFile.getSelectedFile();
            taCode.setText(file.toString());
            
            // Retrieve filename
            String filename = parseFileName(file.toString());
            
            // Adjust codes tabbed pane
            if(tpCode.getTabCount() == 1 && tpCode.getTitleAt(0).equals("[No Name]")){
                tpCode.setTitleAt(0, filename);
                ReadFile rf = new ReadFile(this.file);
                taCode.setText(rf.read());
            }else{
                // Open another tab
            }   
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompilerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompilerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompilerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompilerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompilerGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseFile;
    private javax.swing.JButton btnCompile;
    private javax.swing.JButton btnNewFile;
    private javax.swing.JButton btnOpenFile;
    private javax.swing.JFileChooser fcOpenFile;
    private javax.swing.JTree fileTree;
    private javax.swing.JMenuItem itemNewFile;
    private javax.swing.JMenuItem itemOpenFile;
    private javax.swing.JMenuItem itemQuit;
    private javax.swing.JMenuItem itemSave;
    private javax.swing.JMenuItem itemSaveAs;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JTextArea taCode;
    private javax.swing.JTextArea taOutput;
    private javax.swing.JTabbedPane tpCode;
    private javax.swing.JTabbedPane tpOutput;
    // End of variables declaration//GEN-END:variables
}
